// Generated from data/community-directory-businesses.csv and data/community-directory-creators.csv.
window.SV_DIRECTORY = [
  {
    "slug": "adreno-melbourne",
    "name": "ADRENO Melbourne",
    "category": "Spearfishing Stores",
    "categories": [
      "Spearfishing Stores"
    ],
    "type": "Spearfishing and freediving retail store",
    "region": "Melbourne south-east",
    "location": "Cheltenham, VIC",
    "serviceArea": "Melbourne, Victoria and online Australia-wide",
    "description": "ADRENO Melbourne is a Victorian branch of a national dive retailer with an explicit spearfishing and freediving gear focus. The Melbourne store is relevant because it provides in-person fitting and advice for spearguns, wetsuits, fins, floats, masks and other equipment used by Victorian spearos and freedivers.",
    "services": [
      "Spearfishing gear",
      "freediving gear",
      "wetsuits",
      "fins",
      "masks",
      "spearguns",
      "online and in-store retail"
    ],
    "website": "https://adreno.com.au/",
    "instagram": "https://www.instagram.com/adrenospearfishing/",
    "youtube": "https://www.youtube.com/user/AdrenoSpearfishing",
    "email": "",
    "phone": "",
    "logo": "",
    "source": "https://adreno.com.au/",
    "secondarySource": "https://adreno.com.au/blogs/news/welcome-to-adreno-melbourne",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "National brand but clear Melbourne store and explicit spearfishing/freediving range. Official logo URL should be pulled from the live site during asset preparation.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "ballarat-underwater-hockey-club",
    "name": "Ballarat Underwater Hockey Club",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports"
    ],
    "type": "Underwater hockey club",
    "region": "Ballarat",
    "location": "University of Ballarat / Federation University, Mount Helen VIC",
    "serviceArea": "Ballarat and western Victoria",
    "description": "Ballarat Underwater Hockey Club is listed by the Victorian Underwater Hockey Commission as a place to play underwater hockey in Victoria. Public club-directory sources list the club as active at the University of Ballarat / Mount Helen pool, with regular Monday night sessions and beginners welcome.",
    "services": [
      "Underwater hockey",
      "Monday night training",
      "beginner participation",
      "club play",
      "Victorian underwater hockey pathway"
    ],
    "website": "https://vuhc.org.au/find-a-game/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "0417 143 231",
    "logo": "",
    "source": "https://vuhc.org.au/find-a-game/",
    "secondarySource": "https://www.uwhmap.com/clubs/all",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Added by request. VUHC lists Ballarat Underwater Hockey Club; UWH Map lists Ballarat as active at University of Ballarat, Mount Helen. PlaySport lists Bruce Hollioake as contact.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "club-spearfish",
    "name": "Club Spearfish",
    "category": "Clubs",
    "categories": [
      "Clubs"
    ],
    "type": "Spearfishing club",
    "region": "Victoria",
    "location": "Victoria",
    "serviceArea": "Victoria",
    "description": "Club Spearfish appears in the AUF spearfishing club listings under Victoria and is also referenced by local freediving guides. It should be treated as a provisional community directory entry until its current official website, contacts and active meeting details are manually confirmed.",
    "services": [
      "Spearfishing club",
      "AUF club pathway",
      "Victorian spearfishing community"
    ],
    "website": "https://aufspearfishing.com.au/clubs/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "",
    "source": "https://aufspearfishing.com.au/clubs/",
    "secondarySource": "https://freedivingmelbourne.org/",
    "lastUpdated": "2026-09-28",
    "confidence": "Medium",
    "researchNotes": "Included because AUF lists it under Victoria. Current official club website and contact details were not reliably confirmed.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "dive-gear-australia",
    "name": "Dive Gear Australia",
    "category": "Spearfishing Stores",
    "categories": [
      "Spearfishing Stores"
    ],
    "type": "Dive, freediving and spearfishing retail store",
    "region": "Melbourne south-east",
    "location": "Hallam, VIC",
    "serviceArea": "Melbourne, Victoria and online Australia-wide",
    "description": "Dive Gear Australia is a Hallam store that sells scuba, snorkelling, freediving and spearfishing equipment. It qualifies for this directory because its shop navigation and public contact pages explicitly include freediving and spearfishing gear, with an in-store Victorian presence for equipment advice and click-and-collect.",
    "services": [
      "Freediving gear",
      "spearfishing gear",
      "masks",
      "fins",
      "wetsuits",
      "floats",
      "accessories",
      "equipment servicing"
    ],
    "website": "https://divegearaustralia.com.au/",
    "instagram": "",
    "youtube": "",
    "email": "sales@divegearaustralia.com.au",
    "phone": "03 9702 3694",
    "logo": "",
    "source": "https://divegearaustralia.com.au/shop/",
    "secondarySource": "https://divegearaustralia.com.au/contact-dive-shop/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Included on explicit freediving and spearfishing retail basis, not as a scuba-only listing.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "drifters-freediving",
    "name": "Drifters Freediving",
    "category": "Freediving Schools",
    "categories": [
      "Freediving Schools"
    ],
    "type": "Freediving and spearfishing school",
    "region": "Melbourne",
    "location": "Melbourne, VIC",
    "serviceArea": "Melbourne, Victoria and selected retreat locations",
    "description": "Drifters Freediving is a Melbourne-based freediving provider that advertises AIDA courses, specialty retreats and beginner spearfishing instruction. It is relevant to a Victorian community directory because it explicitly offers spearfishing education as well as freediving training, though public community commentary should be reviewed before any endorsement-style placement.",
    "services": [
      "AIDA freediving courses",
      "beginner spearfishing course",
      "retreats",
      "pool and open-water training"
    ],
    "website": "https://driftersfreediving.com/",
    "instagram": "https://www.instagram.com/driftersfreediving/",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "../assets/freediving-schools/drifters-freediving.png",
    "source": "https://driftersfreediving.com/beginner-spearfishing",
    "secondarySource": "https://freedivingmelbourne.org/guides/drifters-freediving-review",
    "lastUpdated": "2026-09-28",
    "confidence": "Medium",
    "researchNotes": "Include with care. A public guide notes community concerns about training standards and conduct, so this should be manually reviewed before prominent promotion.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "freedive-geelong",
    "name": "Freedive Geelong",
    "category": "Freediving Schools",
    "categories": [
      "Freediving Schools"
    ],
    "type": "Freediving school and charter provider",
    "region": "Geelong, Bellarine and Surf Coast",
    "location": "Geelong / Queenscliff, VIC",
    "serviceArea": "Geelong, Melbourne, Queenscliff, Portsea and the Surf Coast",
    "description": "Freedive Geelong is a Geelong-based freediving school created by James Cini, with a stated focus on Victoria, the Great Southern Reef and building safe, capable freedivers and spearfishers. Its public pages advertise PADI freediving courses and certified self-guided freedive sessions from Queenscliff or Portsea.",
    "services": [
      "PADI Basic Freediver",
      "PADI Freediver open-water course",
      "PADI Advanced Freediver",
      "certified self-guided freedive sessions",
      "charter-style freedive sessions"
    ],
    "website": "https://www.freedivegeelong.com/",
    "instagram": "https://www.instagram.com/freedivegeelong/",
    "youtube": "",
    "email": "info@freedivegeelong.com",
    "phone": "+61 401 108 781",
    "logo": "",
    "source": "https://www.freedivegeelong.com/about",
    "secondarySource": "https://www.freedivegeelong.com/service-page/self-guided-freedive",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Added by request. Official pages verify Victorian focus, qualifications, course pathway, contact email and phone. Geelong Times also profiles James Cini and Freedive Geelong.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "geelong-freedivers",
    "name": "Geelong Freedivers",
    "category": "Clubs",
    "categories": [
      "Clubs"
    ],
    "type": "Spearfishing and freediving club",
    "region": "Geelong, Bellarine and south-west Victoria",
    "location": "Geelong, VIC",
    "serviceArea": "Geelong, Bellarine Peninsula, Surf Coast and south-west Victoria",
    "description": "Geelong Freedivers is an AUF-affiliated spearfishing and freediving club established in 2015. The club runs monthly catch-ups and member social dives, with a stated purpose of helping people in south-west Victoria network, train and explore underwater activities with a safety-first community approach.",
    "services": [
      "Monthly club catch-ups",
      "social dives",
      "spearo clinics",
      "competitions",
      "freediving and spearfishing community"
    ],
    "website": "https://geelongfreedivers.org/",
    "instagram": "https://www.instagram.com/geelongfreedivers/",
    "youtube": "https://www.youtube.com/@geelongfreedivers4326/featured",
    "email": "geelongfreedivers@gmail.com",
    "phone": "",
    "logo": "../assets/freediving-schools/geelong-freedivers.webp",
    "source": "https://geelongfreedivers.org/",
    "secondarySource": "https://aufspearfishing.com.au/clubs/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Strong fit for the directory. Club has both official website evidence and AUF listing.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "geelong-underwater-hockey-club",
    "name": "Geelong Underwater Hockey Club",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports"
    ],
    "type": "Underwater hockey club",
    "region": "Geelong",
    "location": "Handbury Centre for Wellbeing, Foreshore Road, Corio VIC 3214",
    "serviceArea": "Geelong and Greater Geelong",
    "description": "Geelong Underwater Hockey Club welcomes people of varied ages and capacities to play underwater hockey in a safe, social and competitive environment. Its website lists Wednesday sessions at the Handbury Centre for Wellbeing, while the Greater Geelong community directory notes beginner gear, junior pathways and come-and-try options.",
    "services": [
      "Underwater hockey",
      "junior and senior games",
      "beginner sessions",
      "come-and-try programs",
      "school programs",
      "Victorian and national pathways"
    ],
    "website": "https://geelongunderwaterhockey.org.au/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "0438 904 961",
    "logo": "",
    "source": "https://geelongunderwaterhockey.org.au/",
    "secondarySource": "https://app.geelongcity.vic.gov.au/directory/item/722.aspx",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Added by request. Public contact email is protected in the Geelong directory, so phone is included and email is left blank until manually verified.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "hoookn-adventures",
    "name": "HOOOKN Adventures",
    "category": "Spearfishing Charters",
    "categories": [
      "Spearfishing Charters",
      "Instagram Accounts",
      "YouTube Channels"
    ],
    "type": "Spearfishing charter operator",
    "region": "Melbourne and Port Phillip region",
    "location": "Melbourne, VIC",
    "serviceArea": "Melbourne, Victoria and beyond",
    "description": "HOOOKN Adventures is a Melbourne-based charter operator that explicitly advertises spearfishing tours, fishing and spearfishing experiences, and adventure retreats. It is the clearest Victorian spearfishing-specific charter found in this pass, with public contact details and social channels tied to its charter offering.",
    "services": [
      "Spearfishing tours",
      "fishing charters",
      "bluewater trips",
      "retreats",
      "filming packages",
      "corporate charters",
      "spearfishing charters",
      "Melbourne boating",
      "travel",
      "film packages",
      "fishing",
      "adventure filming"
    ],
    "website": "https://hoookn.com.au/",
    "instagram": "https://www.instagram.com/hoookn.adventures/",
    "youtube": "https://www.youtube.com/@HOOOKN",
    "email": "benji@hoookn.com.au",
    "phone": "0439 HOOOKN",
    "logo": "",
    "source": "https://hoookn.com.au/",
    "secondarySource": "https://hoookn.com.au/charters/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Only include charter operators like this where spearfishing is explicit. Do not add ordinary fishing charters without a spearfishing page.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "maribyrnong-underwater-hockey-club",
    "name": "Maribyrnong Underwater Hockey Club",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports"
    ],
    "type": "Underwater hockey club",
    "region": "Melbourne inner west",
    "location": "Maribyrnong Aquatic Centre, 1 Aquatic Drive, Maribyrnong VIC 3032",
    "serviceArea": "Maribyrnong and Melbourne inner west",
    "description": "Maribyrnong Underwater Hockey Club is listed by the Victorian Underwater Hockey Commission as a place to play in Victoria. The VUHC club page gives Tuesday evening sessions at the Maribyrnong Aquatic Centre, and local activity listings also show underwater hockey sessions at Maribyrnong.",
    "services": [
      "Underwater hockey",
      "Tuesday night training",
      "beginner and club play",
      "Victorian underwater hockey pathway"
    ],
    "website": "https://vuhc.org.au/find-a-game/footscray-uwh-club/",
    "instagram": "",
    "youtube": "",
    "email": "Daleschalkwijk@gmail.com",
    "phone": "0435 824 603",
    "logo": "",
    "source": "https://vuhc.org.au/find-a-game/footscray-uwh-club/",
    "secondarySource": "https://www.maribyrnong.vic.gov.au/files/assets/public/v/1/community-life-documents/active-maribyrnong/2026-get-active-expo/2026-get-active-expo-timetable-with-hyperlinks.pdf",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Added by request. User wrote Marynbynong; public sources use Maribyrnong. VUHC page names contact Gerry Schalkwijk.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "marlon-quinn-boundless-blue",
    "name": "Marlon Quinn / Boundless Blue",
    "category": "Freediving Schools",
    "categories": [
      "Freediving Schools"
    ],
    "type": "Freediving instructor",
    "region": "Mornington Peninsula",
    "location": "Sorrento, VIC",
    "serviceArea": "Mornington Peninsula and Port Phillip Bay",
    "description": "Marlon Quinn operates from the Mornington Peninsula under the Boundless Blue offering and is publicly described as a long-running Victorian freediving instructor. His profile is relevant for members seeking smaller-format instruction, breathwork-informed freediving training and local peninsula knowledge around Sorrento and nearby ocean sites.",
    "services": [
      "PADI freediving instruction",
      "instructor training",
      "breathwork",
      "ocean confidence training"
    ],
    "website": "https://marlonquinn.com/boundless-blue/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "../assets/freediving-schools/marlon-quinn-boundless-blue.png",
    "source": "https://marlonquinn.com/boundless-blue/",
    "secondarySource": "https://freedivingmelbourne.org/guides/freediving-schools-melbourne",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Mornington Peninsula instructor; manually corrected from a shifted CSV row.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "melbourne-freedivers-club",
    "name": "Melbourne Freedivers Club",
    "category": "Clubs",
    "categories": [
      "Clubs"
    ],
    "type": "Freediving club",
    "region": "Melbourne",
    "location": "Melbourne, VIC",
    "serviceArea": "Melbourne and Victorian freediving sites",
    "description": "Melbourne Freedivers Club is an Australian Freediving Association-affiliated club that encourages safe and supportive freediving. Its website and FAQ emphasise community, pool training, safety induction and member activity rather than paid instruction, so it should be listed as a club rather than a freediving school.",
    "services": [
      "Pool training",
      "safety induction",
      "gear loan",
      "depth trips",
      "member community"
    ],
    "website": "https://melbournefreedivers.org.au/",
    "instagram": "https://www.instagram.com/melbournefreediversclub/",
    "youtube": "",
    "email": "training@melbournefreedivers.org.au",
    "phone": "",
    "logo": "../assets/freediving-schools/melbourne-freedivers-club.png",
    "source": "https://melbournefreedivers.org.au/",
    "secondarySource": "https://melbournefreedivers.org.au/faq/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Do not describe as a coaching service. The club FAQ points new divers to external instructors.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "monash-university-underwater-club",
    "name": "Monash University Underwater Club",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports"
    ],
    "type": "University underwater hockey club",
    "region": "Melbourne south-east",
    "location": "Clayton, VIC",
    "serviceArea": "Monash University and Melbourne south-east",
    "description": "Monash University Underwater Club includes underwater hockey membership through Team Monash. Public university club material describes underwater hockey as part of the club's activity mix, with memberships available for students and the broader community, making it relevant for Victorian underwater-sport pathways.",
    "services": [
      "Underwater hockey membership",
      "university club activity",
      "beginner and community participation"
    ],
    "website": "https://clubsandvarsity.monash.edu/Clubs/Underwater-Club",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "",
    "source": "https://clubsandvarsity.monash.edu/Clubs/Underwater-Club",
    "secondarySource": "https://www.monashclubs.org/About/Monash-Student-Association/2016-Clubs-Guide",
    "lastUpdated": "2026-09-28",
    "confidence": "Medium",
    "researchNotes": "Current Team Monash page confirms underwater hockey membership. Older guide provides fuller description; verify current training times before publishing.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "mr-dive",
    "name": "Mr Dive",
    "category": "Spearfishing Stores",
    "categories": [
      "Spearfishing Stores"
    ],
    "type": "Spearfishing, freediving and dive retail store",
    "region": "Melbourne south-east",
    "location": "Oakleigh South, VIC",
    "serviceArea": "Melbourne and online Australia-wide",
    "description": "Mr Dive is a Melbourne dive shop in Oakleigh South that explicitly describes itself as a specialised spearfishing shop for spearos, scuba divers, snorkellers and freedivers. It is relevant because its public pages advertise spearguns, wetsuits, fins, floats, masks, snorkels and other spearfishing equipment.",
    "services": [
      "Spearfishing gear",
      "freediving gear",
      "spearguns",
      "wetsuits",
      "fins",
      "masks",
      "snorkels",
      "online retail"
    ],
    "website": "https://www.mrdive.com.au/",
    "instagram": "",
    "youtube": "",
    "email": "henryw@mrdive.com.au",
    "phone": "03 8488 9992",
    "logo": "",
    "source": "https://www.mrdive.com.au/spearfishing/",
    "secondarySource": "https://www.mrdive.com.au/about-us/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Clear physical location and explicit spearfishing category. Social links were not verified in this pass.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "salt-sessions-freediving",
    "name": "Salt Sessions Freediving",
    "category": "Freediving Schools",
    "categories": [
      "Freediving Schools"
    ],
    "type": "Freediving school",
    "region": "Melbourne and Mornington Peninsula",
    "location": "Melbourne, VIC",
    "serviceArea": "Melbourne, Port Phillip Bay and Mornington Peninsula",
    "description": "Salt Sessions Freediving is a Melbourne-based freediving school focused on recognised beginner and continuing freediving education. Public sources describe it as a large Victorian training centre with regular local courses, experienced instructors and a pathway for people who want to develop comfort, safety and skills in Victorian waters.",
    "services": [
      "PADI and Molchanovs freediving courses",
      "beginner freediving",
      "advanced training",
      "gear hire",
      "retreats",
      "local club dives"
    ],
    "website": "https://saltsessions.com.au/",
    "instagram": "https://www.instagram.com/salt_sessions_freediving/",
    "youtube": "",
    "email": "",
    "phone": "0431 699 264",
    "logo": "../assets/freediving-schools/salt-sessions-freediving.png",
    "source": "https://saltsessions.com.au/",
    "secondarySource": "https://freedivingmelbourne.org/guides/freediving-schools-melbourne",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Clear Victorian freediving school. Existing Club House logo asset already downloaded from the official site.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "simple-dive-melbourne",
    "name": "Simple Dive Melbourne",
    "category": "Freediving Schools",
    "categories": [
      "Freediving Schools"
    ],
    "type": "Dive and freediving school",
    "region": "Melbourne east",
    "location": "Blackburn South, VIC",
    "serviceArea": "Melbourne and eastern suburbs",
    "description": "Simple Dive Melbourne is a Blackburn South dive business that publicly advertises AIDA freediving alongside scuba and equipment services. It is suitable for the directory because it has a physical Victorian shopfront and a clear freediving training offer rather than being a general scuba-only operator.",
    "services": [
      "AIDA freediving",
      "scuba courses",
      "dive gear retail",
      "equipment support"
    ],
    "website": "https://www.simpledive.com.au/",
    "instagram": "https://www.instagram.com/simpledivemel/",
    "youtube": "",
    "email": "info@simpledive.com.au",
    "phone": "+61 414 907 659",
    "logo": "../assets/freediving-schools/simple-dive-melbourne.png",
    "source": "https://www.simpledive.com.au/pages/about-us",
    "secondarySource": "https://freedivingmelbourne.org/guides/freediving-schools-melbourne",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Physical address and freediving offer are public. Confirm current AIDA course dates before publishing course-specific claims.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "southern-freedivers",
    "name": "Southern Freedivers",
    "category": "Clubs",
    "categories": [
      "Clubs"
    ],
    "type": "Spearfishing club",
    "region": "Melbourne and Victoria-wide",
    "location": "Melbourne, VIC",
    "serviceArea": "Victoria",
    "description": "Southern Freedivers is a volunteer-run Victorian spearfishing club established in 1994. Its website describes competition spearfishing, social dives, member catch-ups and quarterly meetings, making it a strong community directory entry for people seeking spearfishing networks, local knowledge and structured club involvement in Victoria.",
    "services": [
      "Competition spearfishing",
      "social dives",
      "member catch-ups",
      "quarterly meetings",
      "spearfishing community"
    ],
    "website": "https://southernfreedivers.org.au/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "../assets/freediving-schools/southern-freedivers.svg",
    "source": "https://southernfreedivers.org.au/",
    "secondarySource": "https://aufspearfishing.com.au/clubs/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Official site says the club has connected Victorian divers for more than 30 years. Social links should be manually confirmed.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "southern-spearfishing",
    "name": "Southern Spearfishing",
    "category": "Instagram Accounts",
    "categories": [
      "Instagram Accounts"
    ],
    "type": "Instagram creator",
    "region": "Melbourne and Victoria",
    "location": "Melbourne and Victoria",
    "serviceArea": "",
    "description": "This Instagram account appears connected to the same Victorian spearfishing creator presence as Southern Spearfishing on YouTube. It is suitable as a local creator listing if posts are confirmed to feature Victorian spearfishing, local species, dive trips or education rather than unrelated travel-only content.",
    "services": [
      "spearfishing",
      "local catches",
      "Melbourne diving",
      "gear",
      "community"
    ],
    "website": "",
    "instagram": "https://www.instagram.com/southernspearfishing/",
    "youtube": "",
    "email": "",
    "phone": "",
    "logo": "",
    "source": "https://www.instagram.com/southernspearfishing/",
    "secondarySource": "https://poddtoppen.se/podcast/938873281/noob-spearo-podcast/nsp112-melbourne-spearfishing-live-panel-interview",
    "lastUpdated": "2026-09-28",
    "confidence": "Medium",
    "researchNotes": "Instagram content needs a final visual check because search snippets and podcast references verify the handle more strongly than individual posts.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "torelli-spearfishing-australia",
    "name": "Torelli Spearfishing Australia",
    "category": "Spearfishing Stores",
    "categories": [
      "Spearfishing Stores"
    ],
    "type": "Spearfishing equipment maker and retailer",
    "region": "Mornington Peninsula",
    "location": "Capel Sound, VIC",
    "serviceArea": "Victoria and online Australia-wide",
    "description": "Torelli Spearfishing Australia is a Victorian spearfishing equipment brand and factory store based in Capel Sound. Its official pages state that it was founded in Australia in 1996 and supplies wetsuits, spearguns, fins, masks, floats and accessories for recreational and competition spearfishers.",
    "services": [
      "Spearfishing wetsuits",
      "spearguns",
      "freediving fins",
      "masks",
      "snorkels",
      "float systems",
      "accessories",
      "factory store"
    ],
    "website": "https://torelli.com.au/",
    "instagram": "",
    "youtube": "",
    "email": "",
    "phone": "(03) 5987 0693",
    "logo": "",
    "source": "https://torelli.com.au/pages/about",
    "secondarySource": "https://torelli.com.au/pages/contact-us",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Strong Victorian connection through Capel Sound factory store and spearfishing-specific product range.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "victoria-seadragons-underwater-rugby",
    "name": "Victoria Seadragons Underwater Rugby",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports",
      "Instagram Accounts"
    ],
    "type": "Underwater rugby club",
    "region": "Melbourne east",
    "location": "Glen Iris / Box Hill, VIC",
    "serviceArea": "Melbourne and Australian underwater rugby competitions",
    "description": "Victoria Seadragons is the Victorian underwater rugby club listed by Underwater Rugby Australia and Aqualink. Public pages state that beginners are welcome, equipment can be provided, and the team competes around Australia, making it the key Victorian underwater rugby entry for the directory.",
    "services": [
      "Underwater rugby training",
      "beginner sessions",
      "social games",
      "competition",
      "equipment for trials",
      "underwater rugby",
      "breath-hold sport",
      "training",
      "competitions"
    ],
    "website": "https://www.uwra.org.au/play",
    "instagram": "https://www.instagram.com/victoriaseadragonsuwr/",
    "youtube": "",
    "email": "victoriaseadragonsuwr@gmail.com",
    "phone": "",
    "logo": "",
    "source": "https://www.uwra.org.au/play",
    "secondarySource": "https://www.aqualink.com.au/aquatic/swim-clubs-groups/underwater-rugby",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Aqualink says it is the only underwater rugby club in Victoria. UWRA provides current session locations and times.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "victorian-underwater-hockey-commission",
    "name": "Victorian Underwater Hockey Commission",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports",
      "Instagram Accounts"
    ],
    "type": "State underwater hockey body",
    "region": "Victoria",
    "location": "Victoria",
    "serviceArea": "Victoria",
    "description": "The Victorian Underwater Hockey Commission is the peak body for underwater hockey in Victoria. Its site publishes state team, competition and contact information, and lists public committee contact emails and social channels, making it the primary directory entry for members interested in Victorian underwater hockey.",
    "services": [
      "Underwater hockey governance",
      "competitions",
      "state teams",
      "club coordination",
      "enquiries",
      "underwater hockey",
      "Victorian competitions",
      "junior sport",
      "club updates"
    ],
    "website": "https://vuhc.org.au/",
    "instagram": "https://www.instagram.com/victorian_uwh_vuhc/",
    "youtube": "",
    "email": "committee@vuhc.org.au",
    "phone": "",
    "logo": "",
    "source": "https://vuhc.org.au/",
    "secondarySource": "https://vuhc.org.au/contact-us/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Peak body entry. The site spells 'Commision' in its title, but use the standard 'Commission' spelling in display copy.",
    "verifiedOwner": false,
    "recommendations": 0
  },
  {
    "slug": "wonthaggi-underwater-hockey-club",
    "name": "Wonthaggi Underwater Hockey Club",
    "category": "Underwater Sports",
    "categories": [
      "Underwater Sports"
    ],
    "type": "Underwater hockey club",
    "region": "Bass Coast",
    "location": "Wonthaggi, VIC",
    "serviceArea": "Wonthaggi, Bass Coast and Victorian competitions",
    "description": "Wonthaggi Underwater Hockey Club is a Bass Coast club playing at the Bass Coast Aquatic and Leisure Centre. VUHC lists junior and senior Thursday sessions, and local reporting describes Wonthaggi as one of Victoria's major underwater hockey teams with strong junior development.",
    "services": [
      "Underwater hockey juniors",
      "senior training",
      "tournaments",
      "beginner participation"
    ],
    "website": "https://vuhc.org.au/find-a-game/wonthaggi-uwh-club/",
    "instagram": "",
    "youtube": "",
    "email": "wonthaggiunderwaterhockey@hotmail.com",
    "phone": "",
    "logo": "",
    "source": "https://vuhc.org.au/find-a-game/wonthaggi-uwh-club/",
    "secondarySource": "https://www.sgst.com.au/underwater-hockey-making-waves/",
    "lastUpdated": "2026-09-28",
    "confidence": "High",
    "researchNotes": "Official VUHC page provides venue, times, Facebook and email. Good regional sport entry.",
    "verifiedOwner": false,
    "recommendations": 0
  }
];
window.SV_DIRECTORY_CATEGORIES = ['Freediving Schools','Clubs','Spearfishing Stores','Spearfishing Charters','YouTube Channels','Instagram Accounts','Underwater Sports'];

