(() => {
  const $=selector=>document.querySelector(selector);
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const slug=decodeURIComponent(location.pathname.split('/').filter(Boolean).pop()||new URLSearchParams(location.search).get('slug')||'');
  const client=window.supabase&&window.SV_SUPABASE_CONFIG?.url?window.supabase.createClient(window.SV_SUPABASE_CONFIG.url,window.SV_SUPABASE_CONFIG.publishableKey):null;
  let item=(window.SV_DIRECTORY||[]).find(entry=>entry.slug===slug);
  let action='claim';

  const staticListings=new Map((window.SV_DIRECTORY||[]).map(item=>[item.slug,item]));
  function mapLive(value){return{slug:value.slug,name:value.name,category:value.category,categories:value.categories?.length?value.categories:[value.category],type:value.category.replace(/s$/,''),region:value.region,location:value.location||value.region,serviceArea:value.service_area||value.region,description:value.description,services:value.services||[],website:value.website||'',instagram:value.instagram_url||'',youtube:value.youtube_url||'',email:value.contact_email||'',phone:value.phone||'',logo:value.logo_path||staticListings.get(value.slug)?.logo||'',lastUpdated:(value.last_updated||new Date().toISOString()).slice(0,10),verifiedOwner:Boolean(value.owner_verified),recommendations:Number(value.recommendation_count||0)};}
  function render(){
    if(!item){$('[data-not-found]').hidden=false;$('[data-listing-content]').hidden=true;return;}
    document.title=`${item.name} | Spearfishing Victoria Directory`;$('[data-not-found]').hidden=true;$('[data-listing-content]').hidden=false;
    const logo=$('[data-logo]'),logoPanel=logo.closest('.listing-hero-logo');logoPanel.classList.toggle('on-dark',['adreno-melbourne','drifters-freediving','freedive-geelong','geelong-freedivers','marlon-quinn-boundless-blue','melbourne-freedivers-club','simple-dive-melbourne','southern-freedivers','torelli-spearfishing-australia'].includes(item.slug));if(item.logo){logo.src=item.logo.replace(/^\.\.\//,'/');logo.alt=`${item.name} logo`;logo.hidden=false;logoPanel.querySelector('.logo-fallback')?.remove();}else{logo.hidden=true;logoPanel.innerHTML=`<div class="logo-fallback"><i data-lucide="${item.category==='Instagram Accounts'?'instagram':item.category==='YouTube Channels'?'youtube':'waves'}"></i><strong>${escapeHtml(item.name.split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase())}</strong></div>`;}
    const itemCategories=item.categories?.length?item.categories:[item.category];$('[data-category]').textContent=itemCategories.join(' · ');$('[data-name]').textContent=item.name;$('[data-location]').textContent=item.location;$('[data-type]').textContent=itemCategories.join(', ');$('[data-description]').textContent=item.description;
    const primaryUrl=item.website||item.instagram||item.youtube,primaryLabel=item.website?'Visit website':item.instagram?'View Instagram':'Watch on YouTube',primaryIcon=item.website?'external-link':item.instagram?'instagram':'youtube';$('[data-website]').href=primaryUrl||'#';$('[data-website]').innerHTML=`<i data-lucide="${primaryIcon}"></i> ${primaryLabel}`;$('[data-website]').hidden=!primaryUrl;$('[data-services]').innerHTML=item.services.map(service=>`<span>${escapeHtml(service)}</span>`).join('');$('[data-services]').closest('.content-panel').querySelector('h2').textContent=['Instagram Accounts','YouTube Channels'].includes(item.category)?'Topics':'Services';
    $('[data-detail-location]').textContent=item.location;$('[data-service-area]').textContent=item.serviceArea;$('[data-service-area]').closest('div').hidden=!item.serviceArea;$('[data-owner-status]').textContent=item.verifiedOwner?'Verified owner':'Not yet claimed';$('[data-updated]').textContent=new Intl.DateTimeFormat('en-AU',{dateStyle:'medium'}).format(new Date(`${item.lastUpdated}T00:00:00`));
    const links=[['Website',item.website,'globe-2'],['Instagram',item.instagram,'instagram'],['YouTube',item.youtube,'youtube'],['Email',item.email?`mailto:${item.email}`:'','mail'],['Phone',item.phone?`tel:${item.phone.replace(/[^+\d]/g,'')}`:'','phone']].filter(([,url])=>url);
    $('[data-links]').innerHTML=links.map(([label,url,icon])=>`<a href="${escapeHtml(url)}" target="${url.startsWith('http')?'_blank':'_self'}" rel="noopener noreferrer"><span><i data-lucide="${icon}"></i> ${label}</span><i data-lucide="arrow-up-right"></i></a>`).join('');$('[data-media-panel]').hidden=!links.length;
    $('[data-recommendations]').textContent=item.recommendations;$('[data-recommend-copy]').textContent=item.recommendations>=5?'This listing is Community Recommended.':`${5-item.recommendations} more recommendations needed to qualify.`;
    if(window.lucide)window.lucide.createIcons({attrs:{width:16,height:16}});
  }
  async function loadLive(){if(!client)return;const{data,error}=await client.rpc('get_public_directory');const found=!error&&data?.find(entry=>entry.slug===slug);if(found){item=mapLive(found);render();}}
  function openAction(next){action=next;const isClaim=next==='claim';$('[data-dialog-title]').textContent=isClaim?'Claim this listing':next==='report'?'Report this listing':'Recommend this listing';$('[data-dialog-copy]').textContent=isClaim?'Approval gives control of this public page. Provide evidence a moderator can verify independently; a request alone is not enough.':next==='report'?'Tell moderators what appears inaccurate, unsafe or out of date.':'Recommendations are public community signals. Add an optional note about your experience.';$('[data-dialog-submit]').textContent=isClaim?'Send ownership claim':next==='report'?'Send report':'Recommend';$('[data-claim-fields]').hidden=!isClaim;$('[data-claim-consent]').hidden=!isClaim;$('[data-details-label]').textContent=isClaim?'How can we verify your authority?':'Details';const form=$('[data-action-form]');['claimant_role','business_email','verification_url','contact_consent'].forEach(name=>{form.elements[name].required=isClaim;});$('[data-action-dialog]').showModal();}
  document.querySelectorAll('[data-claim]').forEach(button=>button.addEventListener('click',()=>openAction('claim')));$('[data-report]').addEventListener('click',()=>openAction('report'));$('[data-recommend]').addEventListener('click',()=>openAction('recommend'));$('[data-close-dialog]').addEventListener('click',()=>$('[data-action-dialog]').close());$('[data-action-dialog]').addEventListener('click',event=>{if(event.target===$('[data-action-dialog]'))$('[data-action-dialog]').close();});
  $('[data-action-form]').addEventListener('submit',async event=>{event.preventDefault();const status=$('[data-form-status]'),submit=$('[data-dialog-submit]');if(!client){status.textContent='Member actions are temporarily unavailable. Please try again shortly.';return;}const{data:{session}}=await client.auth.getSession();if(!session){status.textContent='Please sign in, then return to this listing to send your claim.';return;}status.textContent='Sending...';submit.disabled=true;const form=event.currentTarget,details=form.elements.details.value.trim(),rpc=action==='claim'?'claim_directory_listing':action==='report'?'report_directory_listing':'recommend_directory_listing';const params=action==='claim'?{listing_slug:item.slug,claim_role:form.elements.claimant_role.value.trim(),claim_business_email:form.elements.business_email.value.trim(),claim_verification_url:form.elements.verification_url.value.trim(),request_details:details,claim_contact_consent:form.elements.contact_consent.checked}:action==='recommend'?{listing_slug:item.slug,recommendation_note:details}:{listing_slug:item.slug,request_details:details};let{error}=await client.rpc(rpc,params);
    // Keep ownership claims working while the verified-claims database update rolls out.
    if(action==='claim'&&error&&(/claim_directory_listing/i.test(error.message||'')||error.code==='PGRST202')){
      const legacy=await client.rpc('claim_directory_listing',{listing_slug:item.slug,request_details:`Role: ${params.claim_role}\nOrganisation email: ${params.claim_business_email}\nVerification page: ${params.claim_verification_url}\n\n${details}`});
      error=legacy.error;
    }
    submit.disabled=false;status.textContent=error?`We couldn't send this claim: ${error.message||'Please try again.'}`:action==='claim'?'Claim received. A moderator will independently verify the details before granting access.':action==='report'?'Report received. Thank you for helping keep the directory useful.':'Recommendation recorded.';if(!error){form.reset();loadLive();}
  });
  render();loadLive();
})();
